# Generated by Django 6.0.6 on 2026-06-30 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CRMA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('nom', models.CharField(max_length=255)),
                ('adresse', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('ccp_compte', models.CharField(max_length=20)),
                ('ccp_cle', models.CharField(max_length=5)),
                ('badr_compte', models.CharField(blank=True, max_length=30)),
                ('bna_compte', models.CharField(blank=True, max_length=30)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
