# Generated by Django 6.0.6 on 2026-06-30 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BureauLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('nom', models.CharField(max_length=255)),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('crma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bureaux_locaux', to='core.crma')),
            ],
            options={
                'unique_together': {('crma', 'code')},
            },
        ),
    ]
