# Generated by Django 6.0.6 on 2026-07-01 22:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profil'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LigneEncaissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('numero_contrat', models.CharField(blank=True, max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('heure', models.TimeField(auto_now_add=True)),
                ('bureau_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encaissements', to='core.bureaulocal')),
                ('saisi_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encaissements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-heure'],
            },
        ),
    ]
