# Generated by Django 6.0.6 on 2026-07-02 01:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ligneencaissement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BonVersement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_versement', models.CharField(choices=[('CCP', 'Versement CCP'), ('BADR', 'Virement BADR'), ('BNA', 'Virement BNA')], max_length=10)),
                ('numero_emission', models.CharField(max_length=50, unique=True)),
                ('montant_jour', models.DecimalField(decimal_places=2, max_digits=12)),
                ('droits_poste', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('montant_a_verser', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_emission', models.DateField(auto_now_add=True)),
                ('date_versement', models.DateField()),
                ('bureau_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bons_versement', to='core.bureaulocal')),
                ('emis_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bons_versement', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_emission', '-id'],
            },
        ),
    ]
