# Generated by Django 6.0.6 on 2026-07-07 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_bonversement'),
    ]

    operations = [
        migrations.AddField(
            model_name='crma',
            name='deduire_droits_ccp',
            field=models.BooleanField(default=True, verbose_name='Déduire les droits Algérie Poste (CCP)'),
        ),
    ]
