# Generated by Django 6.0.6 on 2026-07-08 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_crma_deduire_droits_ccp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueMutation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_mutation', models.DateTimeField(auto_now_add=True)),
                ('ancien_bl', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mutations_depart', to='core.bureaulocal')),
                ('effectuee_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mutations_effectuees', to=settings.AUTH_USER_MODEL)),
                ('nouveau_bl', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mutations_arrivee', to='core.bureaulocal')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mutations', to='core.profil')),
            ],
            options={
                'ordering': ['-date_mutation'],
            },
        ),
    ]
