# Generated by Django 6.0.7 on 2026-07-09 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_historiquemutation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bonversement',
            name='annule_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bonversement',
            name='annule_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bons_annules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bonversement',
            name='remplace_bon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remplace_par', to='core.bonversement'),
        ),
        migrations.AddField(
            model_name='bonversement',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('CONFIRME', 'Confirmé'), ('ANNULE', 'Annulé')], default='BROUILLON', max_length=10),
        ),
    ]
